name: "Pull Request Template"
description: "새로운 기능 추가 또는 버그 수정 시 작성해주세요."
body:
  - type: markdown
    attributes:
      value: |
        <!-- PR 생성 전 아래 내용을 확인하고 작성해주세요 -->
  - type: input
    id: title
    attributes:
      label: "📌 PR 제목"
      description: "간결하고 명확하게 작성 (예: 사용자 로그인 기능 추가)"
      placeholder: "예: 게시글 좋아요 기능 구현"
      required: true
  - type: input
    id: issue
    attributes:
      label: "🔗 관련 이슈 번호"
      description: "예: #123"
      placeholder: "#"
      required: false
  - type: textarea
    id: description
    attributes:
      label: "📝 변경 사항 요약"
      description: "무엇을, 왜 변경했는지 간략히 작성"
      placeholder: |
        - 로그인 API 엔드포인트 추가  
        - JWT 인증 로직 수정
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: "✅ 체크리스트"
      options:
        - label: 코드 빌드 및 컴파일 통과
          value: build
        - label: 단위/통합 테스트 통과
          value: tests
        - label: 문서/주석 업데이트 완료
          value: docs
      required: true
