server:
  port: 8090
aws:
  secretsmanager:
    region: ap-northeast-2

spring:
  config:
    import:
      - 'aws-secretsmanager:/secret/closet'
  batch:
    job:
      name: COORDINATE_JOB
      enabled: true
    jdbc:
      initialize-schema: never

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info
    project.closet.batch: info
    # JdbcTemplate가 실행하는 SQL을 찍음
    org.springframework.jdbc.core: info
    #    # 바인딩 값(PreparedStatement.setXxx ...)까지 보고 싶으면 TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: info
    #    # (선택) 배치 JDBC 관련 추가 로그
    org.springframework.batch.item.database: info
