server:
  port: 8090
aws:
  secretsmanager:
    region: ap-northeast-2

spring:
  config:
    import:
      - 'aws-secretsmanager:/secret/closet'
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info
    project.closet.batch: info
