spring:
  application:
    name: ${SPRING_APP_NAME:closet-batch}
    time-zone: "Asia/Seoul"

  main:
    web-application-type: none

  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/closet
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  batch:
    job:
      name: COORDINATE_READ_JOB
      enabled: true
    jdbc:
      initialize-schema: always

closet:
  kakao:
    api:
      key: ${KAKAO_API_KEY}
  weather:
    api:
      key: ${WEATHER_API_KEY}
  storage:
    s3:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET_NAME}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600} # (기본값: 10분)

# Logging
logging:
  level:
    root: info
    project.closet.batch: debug
    # JdbcTemplate가 실행하는 SQL을 찍음
    org.springframework.jdbc.core: DEBUG
#    # 바인딩 값(PreparedStatement.setXxx ...)까지 보고 싶으면 TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
#    # (선택) 배치 JDBC 관련 추가 로그
    org.springframework.batch.item.database: DEBUG
